src/Success/Bundle/ViewBundle/Form/Type/GoalFormType.php
<?php
namespace Success\Bundle\ViewBundle\Form\Type;

use Success\Bundle\DomainBundle\Entity\Category;
use Success\Bundle\DomainBundle\Entity\Goal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class GoalFormType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', [
                'label' => false,
                'attr'  => [
                    'placeholder' => 'Titel des Ziels'
                ]
            ])
            ->add('description', 'textarea', [
                'label' => false,
                'attr'  => [
                    'placeholder' => 'Beschreibung'
                ]
            ]);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'goal';
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class'    => Goal::class,
            'action'        => '',
        ]);
    }
}

src/Success/Bundle/ViewBundle/Controller/GoalController.php
<?php

namespace Success\Bundle\ViewBundle\Controller;

use Success\Bundle\DomainBundle\Entity\Category;
use Success\Bundle\DomainBundle\Entity\Goal;
use Success\Bundle\DomainBundle\Entity\Step;
use Success\Bundle\DomainBundle\Entity\User;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Response;

class GoalController extends BaseController
{
    /**
     * @param Category $category
     * @return Response
     *
     * @ParamConverter("category", class="Success\Bundle\DomainBundle\Entity\Category")
     */
    public function indexAction(Category $category)
    {
        return $this->render('SuccessViewBundle:Goal:index.html.twig', ['category' => $category]);
    }

    /**
     * @param Request $request
     * @param Category $category
     * @return JsonResponse
     *
     * @ParamConverter("category", class="Success\Bundle\DomainBundle\Entity\Category")
     */
    public function newAction(Request $request, Category $category)
    {
        $goal = new Goal();
        $goal->setCategory($category);

        $actionURL = $this->generateUrl('success_goal_new', ['slug' => $category->getSlug()]);
        return $this->renderForm($request, $goal, 'new', null, ['action' => $actionURL]);
    }

    /**
     * @param Request $request
     * @param Goal $goal
     * @return JsonResponse
     *
     * @ParamConverter("goal", class="Success\Bundle\DomainBundle\Entity\Goal")
     */
    public function editAction(Request $request, Goal $goal)
    {
        $actionURL = $this->generateUrl('success_goal_edit', ['slug' => $goal->getSlug(), 'category' => $goal->getCategory()->getSlug()]);
        return $this->renderForm($request, $goal, 'edit', null, ['action' => $actionURL]);
    }

    /**
     * @param Goal $goal
     * @return Response
     * @ParamConverter("goal", class="Success\Bundle\DomainBundle\Entity\Goal")
     */
    public function showAction(Goal $goal)
    {
        return $this->render('@SuccessView/Goal/single.html.twig', ['goal' => $goal]);
    }


    /**
     * @param Request $request
     * @param Goal $goal
     * @return JsonResponse
     * @ParamConverter("goal", class="Success\Bundle\DomainBundle\Entity\Goal")
     */
    public function newStepAction(Request $request, Goal $goal)
    {
        $step = new Step();
        $step->setGoal($goal);

        $actionURL = $this->generateUrl('success_step_new', ['slug' => $goal->getSlug()]);
        return $this->renderForm($request, $step, 'new', null, ['action' => $actionURL]);
    }
}

src/Success/Bundle/ViewBundle/Resources/views/Goal/index.html.twig
{% extends 'base.html.twig' %}
{% import '@SuccessView/Macros/voting.html.twig' as voteButtons %}
{% block header %}
    <h1>{{ category.name }}</h1>
{% endblock %}
{% block body %}
    {% set goals = category.goals %}
    <ul class="list-group">
        {% for goal in goals %}
            <li class="goal list-group-item">
                <a href="{{ url('success_goal_show', {slug: goal.slug}) }}">{{ goal }}</a>
                <small>
                    <span class="score">{{ goal.score }}</span>
                    <span class="voting">{{ voteButtons.up(goal) }}{{ voteButtons.down(goal) }}</span>
                </small>
            </li>
        {% endfor %}
        <a href="{{ url('success_goal_new', {slug: category.slug}) }}">+ Ziel hinzufügen</a>
    </ul>
{% endblock %}

src/Success/Bundle/ViewBundle/Resources/views/Goal/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_3_layout.html.twig' %}
{% block body %}
{{ form(form) }}
{% endblock %}

src/Success/Bundle/ViewBundle/Resources/views/Goal/single.html.twig
{% import '@SuccessView/Macros/voting.html.twig' as voteButtons %}
{% extends 'base.html.twig' %}
{% block header %}
    <h1>
        {{ goal.title }}
        <small>
            <span class="score">{{ goal.score }}</span>
            <span class="voting">{{ voteButtons.up(goal) }}{{ voteButtons.down(goal) }}</span>
        </small>
    </h1>
{% endblock %}
{% block body %}
    <div class="row">
        {{ goal.description }}
    </div>
    <div class="row">
        {% for step in goal.steps %}
            {% include '@SuccessView/Step/single.html.twig' %}
        {% endfor %}
    </div>
    <div class="row">
        <a href="{{ url('success_step_new', {'slug': goal.slug}) }}">+ Fortschritt hinzufügen</a>
    </div>
    <div class="row">
        {{ include('@SuccessComment/Comment/index.html.twig', {'target': goal}) }}
    </div>
{% endblock %}
{% block footer %}
    <small>Erstellt am {{ goal.createdAt|date("d.m.Y") }}</small>
{% endblock %}